# Generated by Django 6.0.7 on 2026-07-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='رقم الجوال للتواصل', max_length=15, verbose_name='رقم الجوال')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('is_kitchen_owner', models.BooleanField(default=False, verbose_name='صاحب مطبخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
