# Generated by Django 6.0.7 on 2026-08-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_kitchen_owner',
        ),
    ]
