# Generated by Django 6.0.7 on 2026-07-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الإدام')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر النفر الواحد بدون الأرز', max_digits=10, verbose_name='سعر النفر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='protein/', verbose_name='صورة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الإدام',
                'verbose_name_plural': 'الإدامات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الأرز')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر النفر الواحد بدون الإدام', max_digits=10, verbose_name='سعر النفر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rice/', verbose_name='صورة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'نوع الأرز',
                'verbose_name_plural': 'أنواع الأرز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField(help_text='كم شخص سيتناول الوجبة؟', verbose_name='عدد النفار')),
                ('meal_time', models.CharField(choices=[('غداء', 'غداء'), ('عشاء', 'عشاء')], max_length=10, verbose_name='الميعاد')),
                ('phone', models.CharField(help_text='رقم الجوال للتواصل', max_length=15, verbose_name='رقم الجوال')),
                ('notes', models.TextField(blank=True, help_text='مثل: بدون بهارات، زيادة أرز...', null=True, verbose_name='ملاحظات إضافية')),
                ('rice_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='سعر الأرز للنفر')),
                ('protein_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='سعر الإدام للنفر')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد التجهيز', 'قيد التجهيز'), ('جاهز', 'جاهز'), ('مكتمل', 'مكتمل'), ('ملغي', 'ملغي')], default='جديد', max_length=20, verbose_name='الحالة')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('pickup_time', models.DateTimeField(blank=True, help_text='يحدده صاحب المطبخ', null=True, verbose_name='وقت الاستلام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='الزبون')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.protein', verbose_name='الإدام')),
                ('rice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.ricetype', verbose_name='نوع الأرز')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل التغيير',
                'verbose_name_plural': 'سجل التغييرات',
                'ordering': ['-changed_at'],
            },
        ),
    ]
