# Generated by Django 6.0.7 on 2026-08-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='image',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ricetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ricetype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ricetype',
            name='updated_at',
        ),
    ]
