# Generated by Django 6.0.7 on 2026-08-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_protein_created_at_remove_protein_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateField(default=datetime.date(2026, 8, 10), help_text='يوم الوجبة  ', verbose_name='يوم موعد الوجبة'),
            preserve_default=False,
        ),
    ]
